### ISSUE TITLE
Support to @Scheduled request metrics

### ISSUE THREAD

**Issue by gilliardmacedo** [marcelorubim/quarkus-monitor#6]
Hello and thank you for this great job. We are working with quarkus-monitor and very satisfied with results. 

Our application are publishing metrics from distinct sources, and we are using schedulers to do this. So, among request metrics(latency in particular), we think is useful that we can view metrics from this schedulers.

I can do this, but I prefer we first decide if it makes sense.

Thank you again!

**Comment by CarlosPanarello** [comment]
Hi, recently we add a new methods in MonitorMetrics class, addRequestEvent and addDependencyEvent, to add new request and dependency events to do so.
